server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #TODO validate로 바꾸기
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: ${BATCH_SIZE}
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: 'Wanted Ground 커뮤니티 API'
    version: 'v1.0.0'

jwt:
  secret: ${JWT_SECRET_TOKEN}
  expiration-ms: ${ACCESS_TOKEN_EXPIRED}
  refresh-expiration-ms: ${REFRESH_TOKEN_EXPIRED}
  refresh-hash-secret: ${REFRESH_TOKEN_HASH}

google:
  auth:
    client-id: ${GOOGLE_CLIENT_KEY}

app:
  upload:
    local-dir: ${LOCAL_UPLOAD_DIR}
    public-base-path: ${PUBLIC_BASE_PATH}
    max-image-bytes: ${MAX_IMAGE_BYTE}
    max-gif-bytes: ${MAX_GIF_BYTES}
    allowed-mime-types: ${ALLOWED_MIME_TYPES}
    cache-period: ${CACHE_PERIOD}
