resources:
  - analysis-template.yml
  - argocd-application.yml
  - namespace.yml
  - nginx_config_map.yml
  - nginx_deployment_service.yml
  - nginx_ingress.yml
  - rollout.yml
  - service-active.yml
  - service-preview.yml
