apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress
  namespace: community
spec:
  ingressClassName: nginx
  rules:
    - host: community.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: community-gateway
                port:
                  number: 80
