apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: community-be
  namespace: community
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: community-be
  template:
    metadata:
      labels:
        app: community-be
    spec:

      volumes:
        - name: app-logs
          emptyDir: {}

      initContainers:
        - name: init-log-dir
          image: potenup/poten_up:sha-87e6276
          command: ["sh", "-c", "mkdir -p /app/monitoring/logs"]
          volumeMounts:
            - name: app-logs
              mountPath: /app/monitoring/logs

      containers:
        - name: app
          image: potenup/poten_up:sha-87e6276
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: community-be-secret

          # ğŸ”½ ì•± ì»¨í…Œì´ë„ˆì—ë„ ë™ì¼ ê²½ë¡œ ë§ˆìš´íŠ¸
          volumeMounts:
            - name: app-logs
              mountPath: /app/monitoring/logs

  strategy:
    blueGreen:
      activeService: community-be-active
      previewService: community-be-preview
      autoPromotionEnabled: false
